# Generated by Django 6.0.2 on 2026-02-22 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('districts', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_zone',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('carrier', models.CharField(max_length=200)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_days_min', models.PositiveIntegerField(default=1)),
                ('estimated_days_max', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingzone')),
            ],
            options={
                'db_table': 'shipping_method',
                'ordering': ['base_rate'],
            },
        ),
    ]
